version: '3'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000" # Map port 80 to 3000 for public access
    environment:
      NODE_ENV: production
    command: npm run start
